# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Klerio' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Klerio

  pod 'Alamofire'

  target 'KlerioTests' do
    # Pods for testing
  end

end
